#!/usr/bin/env bash
# Code generated from tui/internal/ctl/constants.go; DO NOT EDIT.
# Source this file instead of using raw strings in shell scripts.

# Pane status strings (PaneStatus.Status, styles/status.go, model/*.go).
DOEY_STATUS_BUSY="BUSY"
DOEY_STATUS_READY="READY"
DOEY_STATUS_FINISHED="FINISHED"
DOEY_STATUS_RESERVED="RESERVED"
DOEY_STATUS_ERROR="ERROR"
DOEY_STATUS_WORKING="WORKING"

# Message subjects (IPC .msg files, model/messages.go, model/actions.go).
DOEY_MSG_TASK="task"
DOEY_MSG_STATUS_REPORT="status_report"
DOEY_MSG_WORKER_FINISHED="worker_finished"
DOEY_MSG_TASK_COMPLETE="task_complete"
DOEY_MSG_QUESTION="question"
DOEY_MSG_COMMIT_REQUEST="commit_request"
DOEY_MSG_ERROR="error"
DOEY_MSG_PERMISSION_REQ="permission_request"
DOEY_MSG_QUESTION_ANSWER="question_answer"
DOEY_MSG_CANCEL="cancel"
DOEY_MSG_DISPATCH_TASK="dispatch_task"
DOEY_MSG_NEW_TASK="new_task"
DOEY_MSG_COMPONENT_READY="component_ready"
DOEY_MSG_FREELANCER_DONE="freelancer_finished"

# Message header fields (IPC envelope lines).
DOEY_HEADER_FROM="FROM:"
DOEY_HEADER_SUBJECT="SUBJECT:"
DOEY_HEADER_TARGET_TEAM="TARGET_TEAM:"
DOEY_HEADER_TASK_ID="TASK_ID:"

# Path conventions (runtime dirs, file extensions).
DOEY_RUNTIME_PREFIX="/tmp/doey/"
DOEY_TASK_DIR=".doey/tasks/"
DOEY_TASK_EXT=".task"
DOEY_TASK_RESULT_EXT=".result.json"
DOEY_TASK_SIDECAR_EXT=".json"
DOEY_STATUS_EXT=".status"
DOEY_MSG_EXT=".msg"
DOEY_TRIGGER_EXT=".trigger"
DOEY_STATUS_SUBDIR="status"
DOEY_MESSAGES_SUBDIR="messages"
DOEY_RESULTS_SUBDIR="results"
DOEY_TRIGGERS_SUBDIR="triggers"
DOEY_ISSUES_SUBDIR="issues"
DOEY_ATTACHMENTS_DIR="attachments"

# Pane layout constants (fixed pane indices).
DOEY_PANE_INFO_PANEL=0
DOEY_PANE_BOSS=1
DOEY_PANE_TASKMASTER=2
DOEY_PANE_SUBTASKMASTER=0
DOEY_DASHBOARD_WINDOW=0

# Task field names (parsed from .task files by reader.go).
DOEY_FIELD_TASK_ID="TASK_ID"
DOEY_FIELD_TASK_TITLE="TASK_TITLE"
DOEY_FIELD_TASK_STATUS="TASK_STATUS"
DOEY_FIELD_TASK_SCHEMA_VERSION="TASK_SCHEMA_VERSION"
DOEY_FIELD_TASK_TYPE="TASK_TYPE"
DOEY_FIELD_TASK_DESCRIPTION="TASK_DESCRIPTION"
DOEY_FIELD_TASK_SUBTASKS="TASK_SUBTASKS"
DOEY_FIELD_TASK_CREATED_BY="TASK_CREATED_BY"
DOEY_FIELD_TASK_ASSIGNED_TO="TASK_ASSIGNED_TO"
DOEY_FIELD_TASK_TEAM="TASK_TEAM"
DOEY_FIELD_TASK_TAGS="TASK_TAGS"
DOEY_FIELD_TASK_UPDATED="TASK_UPDATED"
DOEY_FIELD_TASK_CREATED="TASK_CREATED"
DOEY_FIELD_TASK_NOTES="TASK_NOTES"
DOEY_FIELD_TASK_BLOCKERS="TASK_BLOCKERS"
DOEY_FIELD_TASK_RELATED_FILES="TASK_RELATED_FILES"
DOEY_FIELD_TASK_HYPOTHESES="TASK_HYPOTHESES"
DOEY_FIELD_TASK_DECISION_LOG="TASK_DECISION_LOG"
DOEY_FIELD_TASK_ACCEPTANCE="TASK_ACCEPTANCE_CRITERIA"
DOEY_FIELD_TASK_TIMESTAMPS="TASK_TIMESTAMPS"
DOEY_FIELD_TASK_PLAN_ID="TASK_PLAN_ID"
DOEY_FIELD_TASK_RESULT="TASK_RESULT"
DOEY_FIELD_TASK_PHASE="TASK_CURRENT_PHASE"
DOEY_FIELD_TASK_TOTAL_PHASES="TASK_TOTAL_PHASES"
DOEY_FIELD_TASK_FILES="TASK_FILES"
DOEY_FIELD_TASK_COMMITS="TASK_COMMITS"
DOEY_FIELD_TASK_SHORTNAME="TASK_SHORTNAME"

# Task lifecycle statuses (distinct from pane statuses).
DOEY_TASK_STATUS_DRAFT="draft"
DOEY_TASK_STATUS_ACTIVE="active"
DOEY_TASK_STATUS_IN_PROGRESS="in_progress"
DOEY_TASK_STATUS_PAUSED="paused"
DOEY_TASK_STATUS_BLOCKED="blocked"
DOEY_TASK_STATUS_DONE="done"
DOEY_TASK_STATUS_CANCELLED="cancelled"
DOEY_TASK_STATUS_ERROR="error"

# Debug severity levels.
DOEY_SEVERITY_ERROR="ERROR"
DOEY_SEVERITY_WARN="WARN"
DOEY_SEVERITY_INFO="INFO"
DOEY_SEVERITY_DEBUG="DEBUG"
