package remote

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config holds all settings for doey remote provisioning.
type Config struct {
	Provider   string
	APIToken   string
	SSHKeyPath string
	SSHKeyName string
	Region     string
	ServerType string
	AuthMethod string // "oauth", "apikey", "env"
	AuthValue  string
}

// DefaultConfig returns sensible defaults for a new remote setup.
func DefaultConfig() Config {
	return Config{
		Provider:   "hetzner",
		Region:     "fsn1",
		ServerType: "cx22",
		AuthMethod: "oauth",
	}
}

// DefaultConfigPath returns ~/.config/doey/remote.conf.
func DefaultConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return filepath.Join(os.TempDir(), "doey", "remote.conf")
	}
	return filepath.Join(home, ".config", "doey", "remote.conf")
}

// LoadConfig reads a key=value config file. Missing file returns defaults.
func LoadConfig(path string) (Config, error) {
	cfg := DefaultConfig()
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return cfg, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(strings.TrimRight(scanner.Text(), "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key, val := strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
		switch key {
		case "PROVIDER":
			cfg.Provider = val
		case "HETZNER_TOKEN":
			cfg.APIToken = val
		case "SSH_KEY_PATH":
			cfg.SSHKeyPath = val
		case "SSH_KEY_NAME":
			cfg.SSHKeyName = val
		case "REGION":
			cfg.Region = val
		case "SERVER_TYPE":
			cfg.ServerType = val
		case "AUTH_METHOD":
			cfg.AuthMethod = val
		case "AUTH_VALUE":
			cfg.AuthValue = val
		}
	}
	return cfg, scanner.Err()
}

// SaveConfig writes config to a key=value file with 0600 permissions.
// Uses atomic write (temp file + rename) to prevent partial writes on crash.
func SaveConfig(path string, cfg Config) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("# Doey Remote Configuration\n")
	b.WriteString("# Generated by doey remote setup\n\n")
	fmt.Fprintf(&b, "PROVIDER=%s\n", cfg.Provider)
	fmt.Fprintf(&b, "HETZNER_TOKEN=%s\n", cfg.APIToken)
	fmt.Fprintf(&b, "SSH_KEY_PATH=%s\n", cfg.SSHKeyPath)
	fmt.Fprintf(&b, "SSH_KEY_NAME=%s\n", cfg.SSHKeyName)
	fmt.Fprintf(&b, "REGION=%s\n", cfg.Region)
	fmt.Fprintf(&b, "SERVER_TYPE=%s\n", cfg.ServerType)
	fmt.Fprintf(&b, "AUTH_METHOD=%s\n", cfg.AuthMethod)
	fmt.Fprintf(&b, "AUTH_VALUE=%s\n", cfg.AuthValue)

	// Atomic write: temp file in same dir, then rename
	tmp, err := os.CreateTemp(dir, ".remote.conf.*")
	if err != nil {
		return fmt.Errorf("create temp config: %w", err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.WriteString(b.String()); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("write config: %w", err)
	}
	if err := tmp.Chmod(0600); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("set config permissions: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("close config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename config: %w", err)
	}
	return nil
}
